# Generated by Django 2.2.3 on 2019-07-21 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=42)),
                ('created', models.DateTimeField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='groups.Group')),
            ],
        ),
    ]
